### ISSUE TITLE
发生异常: SystemExit 2

### ISSUE THREAD

**Issue by PLA888** [lyh2048/bilibili_video#1]
12.args = parser.parse_args()

**Comment by lyh2048** [comment]
能提供一下更详细的报错信息吗？

**Comment by PLA888** [comment]
是不是我的FFmeg版本安装错了。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月15日 16:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lyh2048/bilibili_video] 发生异常: SystemExit 2 (Issue #1) |

能提供一下更详细的报错信息吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PLA888** [comment]
问题已解决，原来我在D盘没有那个文件夹，但运行你的代码，是真的报错了





是不是我的FFmeg版本安装错了。




***@***.***
***@***.***



---- 回复的原邮件 ----
发件人 ***@***.***>日期 2022年01月15日 16:22 收件人 ***@***.***>抄送至 ***@***.******@***.***>主题 Re: [lyh2048/bilibili_video] 发生异常: SystemExit 2 (Issue #1)
能提供一下更详细的报错信息吗？
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyh2048** [comment]
哦，我忘了判断输出文件夹是否存在了，一会修一下这个bug😜

**Comment by PLA888** [comment]
大佬你会修复这个问题不？今天运行了几个人的代码，发现是同样的问题，网上也找不到解决办法。
运行其他的没什么问题。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月15日 20:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [lyh2048/bilibili_video] 发生异常: SystemExit 2 (Issue #1) |

哦，我忘了判断输出文件夹是否存在了，一会修一下这个bug😜

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyh2048** [comment]
已经解决了
